### ISSUE TITLE
Viewer bug

### ISSUE THREAD

**Issue by sgarnotel** [AmauryG13/atom-freefem-runner#1]
[Enter steps to reproduce:]

1. Open an EDP file
2. Run the script (Ctrl+Alt+F)

**Atom**: 1.34.0 x64
**Electron**: 3.1.1
**OS**: "Arch Linux"
**Thrown From**: [freefempp-runner](https://github.com/atom/freefempp-runner) package 0.1.0

### Stack Trace

Uncaught TypeError: _this2.OutputView.element.innerHTLM is not a function

```
At /home/simon/.atom/packages/atom-freefem-runner/lib/freefempp-runner.js:80

TypeError: _this2.OutputView.element.innerHTLM is not a function
    at /packages/atom-freefem-runner/lib/freefempp-runner.js:80:35)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)
```

### Commands

```
     -0:32.4.0 freefempp-runner:run (input.hidden-input)
```

### Non-Core Packages

```
freefempp-runner 0.1.0 
language-ejs 0.4.0 
language-freefem-official 0.3.0 
```

**Comment by AmauryG13** [comment]
New version is coming, with the viewer support.
