### ISSUE TITLE
Ctrl+Alt+F does not work

### ISSUE THREAD

**Issue by sgarnotel** [AmauryG13/atom-freefem-runner#3]
Ctrl+Alt+F does not work on Linux (Arch Linux)

Atom: 1.34.0
Electron: 3.1.3

Packages -> FreeFem++ runner -> Launch compilation works well
Right-click -> launch compilation for this file works well too

I do not known what else to give you, there is no error message when I use Ctrl+Alt+F

Remark: why not just Alt+R (for run) ?

**Comment by AmauryG13** [comment]
Problem solved !
I forget to add support for linux platform.

Keymap is a personal choice.
I think you can edit key binding at your convenience.

**Comment by sgarnotel** [comment]
Nice!
Thank you
