### ISSUE TITLE
Installation of atom-freefem-runner fails

### ISSUE THREAD

**Issue by paolopiers** [AmauryG13/atom-freefem-runner#5]
Dear Amaury,
thank you for making the execution tool available for Atom.

I am using Atom for Ubuntu 16.04, 64 bit.

I would love to install it to run my scripts without opening the terminal each time.
However, when I try to install the package from the Atom package manager (i.e., the one embedded in the editor), I am prompted this error message.

`Installing “freefem-runner@2.0.0” failed.Hide output…`
`npm ERR! code E404`
`npm ERR! 404 Not Found: https://www.atom.io/api/packages/freefem-runner/versions/2.0.0/tarball`
`npm ERR! A complete log of this run can be found in:`
`npm ERR!     /home/paolo/.atom/.apm/_logs/2019-03-19T00_54_02_920Z-debug.log`

Could you please help me solve it?

Best regards,

Paolo

**Comment by AmauryG13** [comment]
Thanks for the feedback.

I'm working on it.

**Comment by AmauryG13** [comment]
Thanks for the issue, once again.

I solve the problem. You can now reinstall the package with APM.
