### ISSUE TITLE
Follow log

### ISSUE THREAD

**Issue by sgarnotel** [AmauryG13/atom-freefem-runner#6]
When I run a large script with a lot of output, I have to scroll down to follow the execution.

Could you add an automatic following of the output ?

**Comment by AmauryG13** [comment]
Thanks for the feedback.

I will work on it this week. So the new version should be available by the end of the week or the beginning of the next week.

Cheers

**Comment by sgarnotel** [comment]
Nice! Thanks a lot

**Comment by AmauryG13** [comment]
I have working around the issue.
You can check in the [pull request](https://github.com/AmauryG13/atom-freefem-runner/pull/7) I just merged.  

Still the issue with the graphical output remains. It then doesn't scroll to the very bottom of the page but barely.

**Comment by sgarnotel** [comment]
I just test now, it's works well.
Thanks a lot
