### ISSUE TITLE
Kill a job

### ISSUE THREAD

**Issue by sgarnotel** [AmauryG13/atom-freefem-runner#9]
Is there a way to kill a FreeFEM job launched using the runner ?

**Comment by AmauryG13** [comment]
No.
But I'm definitly adding this option.

**Comment by AmauryG13** [comment]
Fix !!
Check the [pull request](https://github.com/AmauryG13/atom-freefem-runner/pull/10)

**Comment by sgarnotel** [comment]
:+1:

**Comment by AmauryG13** [comment]
I just pushed the package to apm

**Comment by sgarnotel** [comment]
Thanks a lot for your reactivity
